Repository AshNumpy/Hisse-senedi-takip-uygulamasi, pull requests merged in 2022-12, with the labels that each got.

#3 machine-learning-fbprophet
  Requirements/packages.py
  data.py
  pages/machine_learning.py
  prophet.ipynb
Labels: devolopment

#4 facebook prophet modelling
  pages/machine_learning.py
  prophet.ipynb
Labels: devolopment

#6 makine öğrenmesi ile tahminleme
  Requirements/packages.py
  __pycache__/data.cpython-310.pyc
  pages/machine_learning.py
Labels: devolopment

#10 homepage front end development
  data.py
  main.py
Labels: devolopment

#11 modulation
  Modules/ML.py
  Modules/graphs.py
  Modules/ts_analysis.py
  __pycache__/data.cpython-310.pyc
  data.py
  main.py
  pages/grafikler.py
  pages/machine_learning.py
  pages/temel_analiz.py
  pages/zaman_serileri.py
  sembol_listesi.py
Labels: devolopment

#14 delete pychace
  __pycache__/data.cpython-310.pyc
Labels: bug

#15 machine learning and ts analysis update, setting sys
  Modules/ML.py
  Modules/sys.py
  Modules/ts_analysis.py
Labels: bug, documentation, devolopment

#16 ml-homepage
  Modules/ML.py
  Modules/__pycache__/ML.cpython-310.pyc
  Modules/__pycache__/graphs.cpython-310.pyc
  Modules/__pycache__/ts_analysis.cpython-310.pyc
  Modules/graphs.py
  Modules/neural_networks.py
  Modules/ts_analysis.py
  __pycache__/data.cpython-310.pyc
  main.py
Labels: devolopment
